### ISSUE TITLE
Redstone with RedLimiter is just... weird

### ISSUE THREAD

**Issue by Zzeyy** [Kiteflow/RedLimiter#1]
I first tried loading RedLimiter with PlugManX,
which I always do to mainly test if the plugin works when being loaded without restarting the server first.

Then I tried to do some simple work with redstone and it was glitching.
I thought it's caused by the plugin being loaded without restarting first, so I restarted the server.
Then I logged back in and tried to work with redstone again with no change.

I couldn't find a Discord invite anywhere, so I'll just post a link for the video here and hope you can view the video.
https://cdn.discordapp.com/attachments/742761477542248468/937102916987260968/2022-01-29_22-45-54.mp4

**Comment by Zzeyy** [comment]
Tried to open the link in a private window and it seems like you're able to download the video.

**Comment by Zzeyy** [comment]
I hope we can come to a solution of this problem, that's why I'm not making any review on the Spigot page yet,
I don't think the plugin is bad or something! 😁 It's just little bit confusing to see redstone do this.

**Comment by Kiteflow** [comment]
This is mostly the intended behaviour, it's stopping redstone blocks from firing again in a certain time limit. However, there is one issue I did notice, with the block still being limited after it was broken. This is an easy fix, which will be implemented in the next update.

**Comment by Zzeyy** [comment]
I'm happy to hear that this issue at least has a meaning. 😊
Can you perhaps explain what should I do to limit the redstone but not to limit it way too much so things work as expected?

**Comment by Kiteflow** [comment]
I'd lower the default timing, and maybe repeater too,  in the config file, that should help bring the redstone more into line with default functionality. It's never going to be 100% normal because the plugin is designed to limit the redstone, but it should help alleviate the issue.
